config/routes.rb
Crafty::Application.routes.draw do

root :to => "topics#index"
  resources :topics do
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :name
  validates :namme, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

def create
  @topic = Topic.new(params[:topic])
  if @topic.save
    flash[:notice] = "Topic has been created."
    redirect_to @project
  else
    # nothing, yet
  end
end

  def show
    @topics = Topic.find(params[:id])
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.update_attributes(params[:topic])
    flash[:notice] = "Topic has been updated."
    redirect_to @topic
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Crafty").join(" - ")
      end
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><% if content_for?(:title) %>
    <%= yield(:title) %>
  <% else %>
    Crafty
  <% end %>
</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <p>
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description "Description" %> <br />
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>

<% end %>

app/views/topics/edit.html.erb
<h2>Edit topic</h2>
<%= render "form" %>

app/views/topics/index.html.erb
<%= link_to "New Topic", new_topic_path %>
<ul>
  <% @topics.each do |topic| %>
    <li><%= link_to topic.name, topic %></li>
  <% end %>
</ul>

app/views/topics/new.html.erb
<h2>New Topic</h2>
<%= form_for(@topic) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %> <br />
    <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/topics/show.html.erb
<h2><%= @topic.name %></h2>
<%= link_to "Edit Topic", edit_topic_path(@topic) %>
<% @title = "Molly - Topics - Crafty" %>